apiVersion: v1
kind: Pod
metadata:
  name: single-node-clip-job-py211
spec:
  securityContext: {}
  restartPolicy: Never
  volumes:
    - name: workdir
      hostPath:
        path: /voyager/ceph/users/haoc3
        type: Directory
  containers:
    - name: gaudi-container
      image: vault.habana.ai/gaudi-docker/1.14.0/ubuntu22.04/habanalabs/pytorch-installer-2.1.1
      # image: vault.habana.ai/gaudi-docker/1.11.0/ubuntu22.04/habanalabs/pytorch-installer-2.0.1:latest
      command: ["/bin/bash", "-c"]  # This keeps the container active for 24 hours
      args:
      - >-
            export HOME=/voyager/ceph/users/haoc3;
            export PATH=$HOME/.local/bin:$PATH;
            hl-smi;
            pip install wandb;
            cd /voyager/research/test_hanaba/open_clip/src;
            sh ../scripts_voyager/test_pretrain.sh
      resources:
        requests:
          cpu: 64
          memory: 360Gi
          habana.ai/gaudi: 8
          hugepages-2Mi: 3800Mi
        limits:
          cpu: 64
          memory: 360Gi
          habana.ai/gaudi: 8
          hugepages-2Mi: 3800Mi
      volumeMounts:
        - name: workdir
          mountPath: /voyager  